# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d8add9e9c35fffe68bc0fefb902fd4ef21674919b17a09fe8318d6f1c11b8a8430ce6bdd1ded6dd81b15af5b717bb5c1323e49ab0d201633ec52c4b9d18334c

test:
  secret_key_base: f3ad219ebc4f062c59e3d797a150c02dbe3b42dfb6cd98d0373a36ff957d4de1495b61f44b56819585d817e07ab9de13744bdfeb9051d6870e13cf0337ac9852

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
